# Generated by Django 3.0.7 on 2020-06-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200612_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='url',
        ),
    ]
